TECH-2406 - Update aws-staging.yaml (#3079)
* Update aws-staging.yaml

Fix error logging and allow for all unset secrets to be shown

* Set secrets as env vars

* moved secrets to check from job level to step level to be more clear

---------

Co-authored-by: Piotr Witek <739075+piotrwitek@users.noreply.github.com>

diff --git a/.github/workflows/aws-staging.yaml b/.github/workflows/aws-staging.yaml
--- a/.github/workflows/aws-staging.yaml
+++ b/.github/workflows/aws-staging.yaml
@@ -26,15 +26,42 @@ jobs:
           node-version: 18.12
 
       - name: Check required secrets
+        env:
+          ADROLL_ADV_ID_STAGING: ${{ secrets.ADROLL_ADV_ID_STAGING }}
+          ADROLL_PIX_ID_STAGING: ${{ secrets.ADROLL_PIX_ID_STAGING }}
+          AJNA_SUBGRAPH_URL_GOERLI: ${{ secrets.AJNA_SUBGRAPH_URL_GOERLI }}
+          AJNA_SUBGRAPH_URL_STAGING: ${{ secrets.AJNA_SUBGRAPH_URL_STAGING }}
+          AJNA_SUBGRAPH_V2_URL_GOERLI: ${{ secrets.AJNA_SUBGRAPH_V2_URL_GOERLI }}
+          AJNA_SUBGRAPH_V2_URL_STAGING: ${{ secrets.AJNA_SUBGRAPH_V2_URL_STAGING }}
+          AWS_API_GATEWAY_URL: ${{ secrets.AWS_API_GATEWAY_URL }}
+          BLOCKNATIVE_API_KEY_STAGING: ${{ secrets.BLOCKNATIVE_API_KEY_STAGING }}
+          BLOG_POSTS_API_KEY: ${{ secrets.BLOG_POSTS_API_KEY }}
+          BLOG_POSTS_API_URL: ${{ secrets.BLOG_POSTS_API_URL }}
+          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
+          INFURA_PROJECT_ID_STAGING: ${{ secrets.INFURA_PROJECT_ID_STAGING }}
+          MAINNET_CACHE_URL_STAGING: ${{ secrets.MAINNET_CACHE_URL_STAGING }}
+          MIXPANEL_KEY_STAGING: ${{ secrets.MIXPANEL_KEY_STAGING }}
+          NOTIFICATIONS_HOST_STAGING: ${{ secrets.NOTIFICATIONS_HOST_STAGING }}
+          NOTIFICATIONS_HOST_STAGING_GOERLI: ${{ secrets.NOTIFICATIONS_HOST_STAGING_GOERLI }}
+          ONE_INCH_API_KEY_STAGING: ${{ secrets.ONE_INCH_API_KEY_STAGING }}
+          ONE_INCH_API_URL_STAGING: ${{ secrets.ONE_INCH_API_URL_STAGING }}
+          PRODUCT_HUB_KEY: ${{ secrets.PRODUCT_HUB_KEY }}
+          REFERRAL_SUBGRAPH_URL_STAGING: ${{ secrets.REFERRAL_SUBGRAPH_URL_STAGING }}
+          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
         run: |
           required_secrets=("NOTIFICATIONS_HOST_STAGING" "NOTIFICATIONS_HOST_STAGING_GOERLI" "AJNA_SUBGRAPH_URL_STAGING" "AJNA_SUBGRAPH_URL_GOERLI" "AJNA_SUBGRAPH_V2_URL_STAGING" "AJNA_SUBGRAPH_V2_URL_GOERLI" "MIXPANEL_KEY_STAGING" "ADROLL_ADV_ID_STAGING" "ADROLL_PIX_ID_STAGING" "MAINNET_CACHE_URL_STAGING" "INFURA_PROJECT_ID_STAGING" "ETHERSCAN_API_KEY" "BLOCKNATIVE_API_KEY_STAGING" "SENTRY_AUTH_TOKEN" "PRODUCT_HUB_KEY" "ONE_INCH_API_KEY_STAGING" "ONE_INCH_API_URL_STAGING" "REFERRAL_SUBGRAPH_URL_STAGING" "AWS_API_GATEWAY_URL" "BLOG_POSTS_API_URL" "BLOG_POSTS_API_KEY")
+          fail=false
           for secret in "${required_secrets[@]}"; do
             secret_value=$(printenv $secret)
             if [[ -z "$secret_value" ]]; then
-              echo "::error ::Secret $secret is not set. Failing the workflow."
-              exit 1
+              echo "::error::Secret $secret is not set"
+              fail=true
             fi
           done
+          if [[ $fail == true ]]; then
+            echo "::error::One or more secrets are not set. Exiting..."
+            exit 1
+          fi
 
       - name: Extract commit hash
         id: vars
